version: '3.8'


services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api: &api
    container_name: quotes-api
    build:
      context: ./
      target: development
    command: npm run dev
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - postgres
    volumes:
      - './:/src'

  prod:
    <<: *api
    build:
      context: production
    command: npm start

  test:
    <<: *api
    build:
      context: test
    command: npm start

volumes:
  db:
    driver: local

